name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: |
            7.0.x
            6.0.x
            5.0.x
            3.1.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: |
            7.0.x
            6.0.x
            5.0.x
            3.1.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
  macOS-latest:
    name: macOS-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: |
            7.0.x
            6.0.x
            5.0.x
            3.1.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
